name: CI/CD

on:
  push:
    branches: [ "main", "CI-CD" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-endpoints:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13.2"

    - name: Create .env file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> .env
        echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
        echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
        
    
    # Cache pip dependencies
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    # Setup the project
    - name: Setup project
      run: |
        pip install --no-cache-dir -r requirements.txt
        python manage.py migrate

    # Create the schema file if it doesn't exist
    - name: Create schema file if not created
      run: |
        if [ ! -f "./schema.yaml" ]; then
          python manage.py spectacular --color --file schema.yaml
        else
          echo "Schema file exists."
        fi

    - name: Build and run Docker container
      run: |
        docker build -t test-planet-api .
        docker --name test-container run -d -p 8000:8000 test-planet-api
    
    - name: List file structure
      run: |
        docker exec test-container find /


    # Run Schemathesis tests
    - name: Run Schemathesis tests
      uses: schemathesis/action@v3
      with:
        schema: "http://0.0.0.0:8000/api/schema/"
        base-url: "http://0.0.0.0:8000"
