name: CI/CD

on:
  push:
    branches: [ "main", "CI-CD" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-endpoints:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13.2"
    
    # Setup the project
    - name: Setup project
      run: |
        python manage.py migrate
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env

    
    # Create the schema file if it doesn't exist
    - name: Create schema file if not created
      run: |
        if [ ! -f "./schema.yaml" ]; then
          ./manage.py spectacular --color --file schema.yml
        else
          echo "Schema file exists."
        fi

    - name: Build and run Docker container
      run: |
        docker build -t test-planet-api .
        docker run -d -p 8000:8000 test-planet-api

    # Run Schemathesis tests
    - name: Run Schemathesis tests
      uses: schemathesis/action@v1
      with:
        schema: "http://localhost:8000/api/schema/"
